### ISSUE TITLE
talks.html takes forever to load

### ISSUE THREAD

**Issue by vanAmsterdam** [laderast/laderast.github.io#1]
Hi this is a complement to your website and talks; I came across your rmd vs qmd talk when googling on quarto vs rmarkdown

I'm considering moving to quarto for my own academic webpage and for future presentations; 

I noticed that the talks.html page takes very long to load and becomes unresponsive (either on safari or chrome), can this be related to quarto presentations / how they're hosted? or maybe it's the youtube playlist plugin?

**Comment by laderast** [comment]
Thanks for pointing this out - there was a JS issue. It should load much faster now.
